-- 创建课程测验关联表
CREATE TABLE `t_course_exam` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '关联记录唯一标识',
  `course_id` bigint unsigned NOT NULL COMMENT '关联课程表ID (t_course.id)',
  `exam_id` int NOT NULL COMMENT '关联试卷表ID (t_exam_paper.id)',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '测验标题',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '测验说明',
  `start_time` datetime NOT NULL COMMENT '测验开始时间',
  `end_time` datetime NOT NULL COMMENT '测验结束时间',
  `duration` int NOT NULL COMMENT '测验时长(分钟)',
  `shuffle_questions` bit(1) DEFAULT b'0' COMMENT '是否打乱题目顺序',
  `show_result` bit(1) DEFAULT b'1' COMMENT '是否显示测验结果',
  `limit_ip` bit(1) DEFAULT b'0' COMMENT '是否限制IP',
  `creator_id` int NOT NULL COMMENT '创建者ID (t_user.id)',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_course_exam` (`course_id`,`exam_id`),
  KEY `idx_course_exam_course_id` (`course_id`),
  KEY `idx_course_exam_exam_id` (`exam_id`),
  KEY `idx_course_exam_creator_id` (`creator_id`),
  CONSTRAINT `fk_course_exam_course` FOREIGN KEY (`course_id`) REFERENCES `t_course` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_course_exam_exam` FOREIGN KEY (`exam_id`) REFERENCES `t_exam_paper` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_course_exam_creator` FOREIGN KEY (`creator_id`) REFERENCES `t_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='存储课程与测验的关联关系'; 